/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.2.0   2019-01-08

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include "string.h"
#include "stdio.h"
#include "stdarg.h"
#include "BlueNRG1_it.h"
#include "BlueNRG_x_device.h"
#include "BlueNRG1_conf.h"
#include "MCAL.h"
#include "ble_const.h"
#include "bluenrg1_stack.h"
#include "bms_config.h"
#include "sleep.h"
#include "App.h"
/* Private typedef */

/* Private define  */
#define WAKEUP_TIMER 0 //Virtual Timer #0
#define WAKEUP_TIMEOUT 5000 // 5 sec
/* Private variables */

/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
  for(int i =0; i<200000; i++);
  SystemInit();
  /* Enable the GPIO Clock */
  SysCtrl_PeripheralClockCmd(CLOCK_PERIPH_GPIO | CLOCK_PERIPH_UART | CLOCK_PERIPH_DMA, ENABLE);
  SystickInit();
  HAL_Delay(500);
  /* BlueNRG-1 stack init */
  uint8_t ret = BlueNRG_Stack_Initialization(&BlueNRG_Stack_Init_params);
  if (ret != BLE_STATUS_AWS_SUCCESS) {
    while(1);
  }
  App_Init();
  /* Infinite loop */
  while(1)
  {
	  App_Process();
      BTLE_StackTick();
	  BlueNRG_Sleep(SLEEPMODE_RUNNING, 0, 0);
#if 0
    /* BlueNRG-1 stack tick */
    BTLE_StackTick();
    /* Application Tick */
    //APP_Tick();
    //iprintf("App Tick\r\n");
    /* Enable Power Save according the Advertising Interval */
    BlueNRG_Sleep(SLEEPMODE_WAKETIMER, 0, 0);
#endif
  }
}

/****************** BlueNRG-1 Sleep Management Callback ********************************/
SleepModes App_SleepMode_Check(SleepModes sleepMode)
{
  return SLEEPMODE_NOTIMER;
}

#ifdef  USE_FULL_ASSERT

/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  */
void assert_failed(uint8_t* file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: iprintf("Wrong parameters value: file %s on line %d\r\n", file, line) */

  /* Infinite loop */
  while (1)
  {
  }
}

#endif
